var Crush40Songs = {
  oyh: { t: "Open Your Heart", y: 1998, g: "Sonic Adventure" },
  dg: { t: "Dangerous Ground", y: 2000, g: "NASCAR Arcade 2000" },
  itw: { t: "Into the Wind", y: 2000, g: "NASCAR Arcade 2000" },
  itl: { t: "In the Lead", y: 2000, g: "NASCAR Arcade 2000" },
  rup: { t: "Revvin' Up", y: 2000, g: "NASCAR Arcade 2000" },
  fm: { t: "Fuel Me", y: 2000, g: "NASCAR Arcade 2000" },
  atw: { t: "All the Way", y: 2000, g: "NASCAR Arcade 2000" },
  wmf: { t: "Watch Me Fly...", y: 2000, g: "NASCAR Arcade 2000" },
  lal: { t: "Live & Learn", y: 2001, g: "Sonic Adventure 2" },
  sh: { t: "Sonic Heroes", y: 2004, g: "Sonic Heroes" },
  wimo: { t: "What I'm Made Of", y: 2004, g: "Sonic Heroes" },
  iam: { t: "I Am... All Of Me", y: 2005, g: "Shadow the Hedgehog" },
  ntb: { t: "Never Turn Back", y: 2005, g: "Shadow the Hedgehog" },
  ahs: { t: "All Hail Shadow", y: 2005, g: "Shadow the Hedgehog" },
  hw: { t: "His World", y: 2006, g: "Sonic the Hedgehog" },
  srih: { t: "Seven Rings In Hand", y: 2007, g: "Sonic and the Secret Rings" },
  kotw: { t: "Knight Of The Wind", y: 2008, g: "Sonic and the Black Knight" },
  ll: { t: "Live Life", y: 2008, g: "Sonic and the Black Knight" },
  ftk: { t: "Fight The Knight", y: 2008, g: "Sonic and the Black Knight" },
  ttf: { t: "Through The Fire", y: 2008, g: "Sonic and the Black Knight" },
  wm: { t: "With Me -Massive Power Mix-", y: 2008, g: "Sonic and the Black Knight" },
  ug: { t: "Un-gravitify", y: 2009, g: "Sonic Riders: Zero Gravity" },
  fw: { t: "Fire Woman", y: 2009, g: "'The Cult' cover" },
  iiy: { t: "Is It You", y: 2009, g: "Crush 40 Original" },
  f: { t: "Free", y: 2010, g: "Sonic Free Riders" },
  soh: { t: "Song Of Hope", y: 2011, g: "Crush 40 Original" },
  sb: { t: "Sonic Boom", y: 2011, g: "Sonic CD" },
  sy: { t: "Sonic Youth", y: 2012, g: "Crush 40 Original" },
  ootd: { t: "One Of Those Days", y: 2012, g: "Crush 40 Original" },
  ra: { t: "Rise Again", y: 2012, g: "Crush 40 Original" },
  twoNights: { t: "2 Nights 2 Remember", y: 2014, g: "Crush 40 Original" },
  bm: { t: "Big Mouth", y: 2014, g: "Crush 40 Original" },
  lotd: { t: "Light Of The Day", y: 2014, g: "Crush 40 Original" },
  dnd: { t: "Down & Dirty", y: 2014, g: "Crush 40 Original" },
  glr: { t: "Green Light Ride", y: 2018, g: "Team Sonic Racing" },
  cmc: { t: "Call Me Crazy", y: 2019, g: "Crush 40 Original" },
};