var Crush40Songs = {
  wimo: "What I'm Made Of",
  iam: "I Am... All Of Me",
  ll: "Live Life",
  lal: "Live & Learn",
  oyh: "Open Your Heart",
  dg: "Dangerous Ground",
  itw: "Into the Wind",
  rup: "Revvin' Up",
  itl: "In the Lead",
  wmf: "Watch Me Fly...",
  fm: "Fuel Me",
  atw: "All the Way",
  sh: "Sonic Heroes",
  ntb: "Never Turn Back",
  ahs: "All Hail Shadow",
  hw: "His World",
  srih: "Seven Rings In Hand",
  kotw: "Knight Of The Wind",
  ftk: "Fight The Knight",
  ttf: "Through The Fire",
  wm: "With Me -Massive Power Mix-",
  ug: "Un-gravitify",
  fw: "Fire Woman",
  iiy: "Is It You",
  f: "Free",
  soh: "Song Of Hope",
  sb: "Sonic Boom",
  sy: "Sonic Youth",
  ootd: "One Of Those Days",
  ra: "Rise Again",
  2n2r: "2 Nights 2 Remember",
  bm: "Big Mouth",
  lotd: "Light Of The Day",
  dnd: "Down & Dirty",
  glr: "Green Light Ride",
  cmc: "Call Me Crazy"
};